### ISSUE TITLE
Linux / OSX version

### ISSUE THREAD

**Issue by phenix117** [rbrasga/SPPD-Team-Manager#1]
Hello,

That's not really an issue but I didn't see any place to put that request: is it possible to have a linux build and/or an OSX version ?

And the perfect thing (but I now I ask too much :p) is it possible to have a command-line only version ?

Bests, ;)

**Comment by rbrasga** [comment]
I was supporting a Linux version, but it's too powerful so I'm only using it to run my cloud service, which I offer for 2$ per month.

For OSX you can run a Windows emulator like bootcamp.

**Comment by graficodestudio** [comment]
"too powerful"...

Is it actually a closed source versus open source matter?

**Comment by rbrasga** [comment]
Too powerful because having access to the source code would make it easy for hackers to manipulate/overload my cheap platform that pulls in all that data.

I'd imagine you can run the team manager pretty easily with `WINE` or another equivalent.

**Comment by graficodestudio** [comment]
Giving third party credentials to closed source software is bad.
Based on what you just stated, your application is relying on "security through obscurity" only.

I just hope you don't get hacked, at least for your cloud users sake.

**Comment by rbrasga** [comment]
> I just hope you don't get hacked, at least for your cloud users sake.

I have no idea what you're talking about. There's no trace of user-identifying data stored anywhere.

If you mean having other people input their username/password, then if the user's were worried, they are free to use 2FA - which is as secure as it gets. On top of that, I tried sharing my SPPD account once without 2FA, and google refused to let them in regardless.

The only security issue is letting hackers upload very specific garbage data, but for that they would have to care a lot about the game. And again, it would only be garbage extremely-specific-team data (not rank, members, or anything like that) for a random team that may or may not exist on the website - as the actual people using the team manager application are anonymous.

It seems you are you interest in contributing to the team manager application? No?

**Comment by graficodestudio** [comment]
So, giving account's email and password to some closed source software is ok, because google implements 2 factor authentication?
I think it actually defeats the entire purpose of 2fa.

As for the anonymity and lack of user related data on your server, well, I guess we have to trust you on your scout's honor.

And yes, I would love to contribute to your team manager software, once you make it open-source, of course.

**Comment by rbrasga** [comment]
> So, giving account's email and password to some closed source software is ok, because google implements 2 factor authentication?

Yes, if you as the user have 2FA enabled for your account. You've seen this, right? https://v1.escapistmagazine.com/news/view/108247-Gabe-Newell-Gives-Away-Personal-Steam-Password

> I would love to contribute to your team manager software, once you make it open-source, of course.

Open Source - No.

Private repository with access to specific user's - Yes. Currently there are 4 other contributors to the source code, which includes the Windows-GUI and Linux-CLI versions.

I would grant you access, but your account has 0 activity, which makes it seem a bit suspicious.

**Comment by graficodestudio** [comment]
I just hope you're joking.

If you aren't joking, please post your github password on this conversation. Let's have a laugh, shall we?

**Comment by rbrasga** [comment]
> I just hope you're joking.

You are the one who is joking.

> If you aren't joking, please post your github password on this conversation.

Why are you being so stubborn? 2FA doesn't only work for me. Anyone's username/password on an account with 2FA will work to test your theory. Gabe Newell, co-founder of Valve/Steam, already posted his username/password.

Lastly, in basic debate the "burden of proof" in this situation is on you to prove that it is possible. Not on me, to prove that it is not possible.

Just admit your mistake, and I'll grant you the access to the source. Damn... I literally grant source code access to anyone who seems legit.
